/**
 *
 * $Id$
 */
package studyprogram.validation;

import org.eclipse.emf.common.util.EList;

import studyprogram.Course;
import studyprogram.Program;

/**
 * A sample validator interface for {@link studyprogram.Department}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DepartmentValidator {
	boolean validate();

	boolean validateCourses(EList<Course> value);
	boolean validatePrograms(EList<Program> value);

	boolean validateName(String value);
}
