/**
 *
 * $Id$
 */
package studyprogram.validation;

import org.eclipse.emf.common.util.EList;

import studyprogram.Base;

/**
 * A sample validator interface for {@link studyprogram.Program}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProgramValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateProgramBase(Base value);
	boolean validateTotalBaseCredits(double value);

	boolean validateTotalCredits(double value);

	boolean validateTotalCredits(EList<Double> value);
}
